<?php
/**
 * Plugin Name: Website screenshots
 * Plugin URI: https://screenshotapi.net
 * Description: A plugin to take website screenshots, powered by screenshotapi.net
 * Version: 1.0
 * Author: Dirk Hoekstra
 * Author URI: https://screenshotapi.net/blog
 */

class WebsiteScreenshot {

    /**
     * @param $data array Can have the following fields:
     *   - url
     *   - width
     *   - height
     *   - thumbnail_width
     * @return bool|string The url of the screenshot or false if an error occurred.
     */
    public static function screenshot($data) {
        $token = self::getToken();

        $query = "https://screenshotapi.net/api/v1/screenshot";
        $query .= "?token={$token}&output=json&url=" . urlencode($data['url']);

        if (array_key_exists('width', $data)) {
            $query .= "&width=" . $data['width'];
        }
        if (array_key_exists('height', $data)) {
            $query .= "&height=" . $data['height'];
        }
        if (array_key_exists('thumbnail_width', $data)) {
            $query .= "&thumbnail_width=" . $data['thumbnail_width'];
        }

        $apiResponse = json_decode(
            file_get_contents($query)
        );

        if (!property_exists($apiResponse, 'screenshot')) {
            return false;
        }

        return $apiResponse->screenshot;
    }

    public static function getToken() {
        return get_option('website_screenshot_options_option_name')['api_key_0'];
    }
}

function websiteScreenshotShortcode($data) {
    $token = WebsiteScreenshot::getToken();
    if (!$token) {
        return ("
            <p style='color:red; font-weight: bold;'>
                Please add your API token in the <a href='/wp-admin/plugins.php?page=website-screenshot-options'>settings page</a>
            </p>
        ");
    }

    $screenshotUrl = WebsiteScreenshot::screenshot($data);

    if (!$screenshotUrl) {
        return ("
            <p style='color:red; font-weight: bold;'>
                Error while getting website screenshot. Make sure the shortcode is correct, 
                and that you've set the correct API token in the 
                <a href='/wp-admin/plugins.php?page=website-screenshot-options'>settings page</a>
            </p>
        ");
    }

    $content = ("
        <p>
            <a 
                style='display:block'
                href='{$data['url']}'
    ");

    if (array_key_exists('target', $data)) {
        $content .= " target='{$data['target']}'";
    }

    // end of the <a> tag.
    $content .= ">";

    $content .= "<img loading='lazy' src='{$screenshotUrl}'";

    if (array_key_exists('alt', $data)) {
        $content .= " alt='{$data['alt']}'";
    }
    if (array_key_exists('class', $data)) {
        $content .= " class='{$data['class']}'";
    }

    // close the tags
    $content .= "/></a></p>";
    return $content;
}

add_shortcode('website-screenshot', 'websiteScreenshotShortcode');


//==============================================================================
//
// Generated by the WordPress Option Page generator
// at http://jeremyhixon.com/wp-tools/option-page/
//
//==============================================================================

class WebsiteScreenshotOptions {
    private $website_screenshot_options_options;

    public function __construct() {
        add_action( 'admin_menu', array( $this, 'website_screenshot_options_add_plugin_page' ) );
        add_action( 'admin_init', array( $this, 'website_screenshot_options_page_init' ) );
    }

    public function website_screenshot_options_add_plugin_page() {
        add_plugins_page(
            'Website screenshot options', // page_title
            'Website screenshot options', // menu_title
            'manage_options', // capability
            'website-screenshot-options', // menu_slug
            array( $this, 'website_screenshot_options_create_admin_page' ) // function
        );
    }

    public function website_screenshot_options_create_admin_page() {
        $this->website_screenshot_options_options = get_option( 'website_screenshot_options_option_name' ); ?>

        <div class="wrap">
            <h2>Website screenshot options</h2>
            <p>Create an account at <a href=\\\"https://screenshotapi.net\\\">screenshotapi.net</a> and paste your API token here.</p>
            <?php settings_errors(); ?>

            <form method="post" action="options.php">
                <?php
                settings_fields( 'website_screenshot_options_option_group' );
                do_settings_sections( 'website-screenshot-options-admin' );
                submit_button();
                ?>
            </form>
        </div>
    <?php }

    public function website_screenshot_options_page_init() {
        register_setting(
            'website_screenshot_options_option_group', // option_group
            'website_screenshot_options_option_name', // option_name
            array( $this, 'website_screenshot_options_sanitize' ) // sanitize_callback
        );

        add_settings_section(
            'website_screenshot_options_setting_section', // id
            'Settings', // title
            array( $this, 'website_screenshot_options_section_info' ), // callback
            'website-screenshot-options-admin' // page
        );

        add_settings_field(
            'api_key_0', // id
            'API key', // title
            array( $this, 'api_key_0_callback' ), // callback
            'website-screenshot-options-admin', // page
            'website_screenshot_options_setting_section' // section
        );
    }

    public function website_screenshot_options_sanitize($input) {
        $sanitary_values = array();
        if ( isset( $input['api_key_0'] ) ) {
            $sanitary_values['api_key_0'] = sanitize_text_field( $input['api_key_0'] );
        }

        return $sanitary_values;
    }

    public function website_screenshot_options_section_info() {

    }

    public function api_key_0_callback() {
        printf(
            '<input class="regular-text" type="text" name="website_screenshot_options_option_name[api_key_0]" id="api_key_0" value="%s">',
            isset( $this->website_screenshot_options_options['api_key_0'] ) ? esc_attr( $this->website_screenshot_options_options['api_key_0']) : ''
        );
    }

}
if ( is_admin() )
    $website_screenshot_options = new WebsiteScreenshotOptions();

// End of generated option page
